name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: yarn install, build
      run: |
        yarn install --frozen-lockfile
        yarn build
      env:
        CI: true
    - name: Deploy
      uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      with:
        args: app deploy